### ISSUE TITLE
缺少com.minimalist.basic.entity.po.table包下面的类

### ISSUE THREAD

**Issue by amadeus5201** [lmq2582609/minimalist-saas#1]
程序包com.minimalist.basic.entity.po.table不存在

**Comment by lmq2582609** [comment]
这个是mybatis-flex生成的，可以参考一下官网：https://mybatis-flex.com/zh/others/apt.html

**Comment by amadeus5201** [comment]
> 这个是mybatis-flex生成的，可以参考一下官网：https://mybatis-flex.com/zh/others/apt.html

好的感谢

**Comment by amadeus5201** [comment]
> 这个是mybatis-flex生成的，可以参考一下官网：https://mybatis-flex.com/zh/others/apt.html

可以把这个配置提上来吗。自己尝试配置了一下 还是不可以用。

**Comment by lmq2582609** [comment]
配置用的都是默认的，你是怎么启动的项目啊？如果用idea的话，报红不用管，启动时会自动生成的。

**Comment by amadeus5201** [comment]
> 配置用的都是默认的，你是怎么启动的项目啊？如果用idea的话，报红不用管，启动时会自动生成的。

idea拉代码之后直接启动的

**Comment by lmq2582609** [comment]
> > 配置用的都是默认的，你是怎么启动的项目啊？如果用idea的话，报红不用管，启动时会自动生成的。
> 
> idea拉代码之后直接启动的

那先执行mvn clear package呢？

**Comment by amadeus5201** [comment]
> > > 配置用的都是默认的，你是怎么启动的项目啊？如果用idea的话，报红不用管，启动时会自动生成的。
> > 
> > 
> > idea拉代码之后直接启动的
> 
> 那先执行mvn clear package呢？

好了 jdk版本太高了忘记切到17了 。
